version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
